And more practice....

In [2]:
import numpy as np
A = np.array([1,2,3])
A

array([1, 2, 3])

In [4]:
B = np.array([[1,2,3],[10,20,30]])
B

array([[ 1,  2,  3],
       [10, 20, 30]])

In [3]:
C = np.array([[1,2,3],[10,20,30],[3,2,1]])
C

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 3,  2,  1]])

In [9]:
D = np.array([1,5.2,2.1,6])
D

array([1. , 5.2, 2.1, 6. ])

In [10]:
E = np.array([[1,5.2,2.1,6],[2,1.1,3,2]])
E

array([[1. , 5.2, 2.1, 6. ],
       [2. , 1.1, 3. , 2. ]])

In [11]:
A.shape

(3,)

In [12]:
D.shape

(4,)

In [5]:
C.shape

(3, 3)

In [14]:
B.shape

(2, 3)

In [15]:
B.dtype

dtype('int64')

In [18]:
type(B)

numpy.ndarray

In [19]:
print(type(B))

<class 'numpy.ndarray'>


In [20]:
E.shape

(2, 4)

In [22]:
B.ndim

2

In [4]:
C.ndim

2

In [33]:
zeros_array = np.zeros((3,2)) 
zeros_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
zeros_array = np.zeros([3,2]) 
print(zeros_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [32]:
new = np.ones((3,5),dtype=float)
new

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
New = np.full((5,3),5)
print(New)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [41]:
# create a 4x4 matrix with the diagonal 1s and the others 0
y = np.eye(4)
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
ex_array = np.full((1,5),2)
print(ex_array)

[[2 2 2 2 2]]


In [51]:
an_array = np.arange(10)
print(an_array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
another_array = np.array([[12,  5,  2,  4],
                          [ 7,  6,  8,  8],
                          [ 1,  6,  7,  7]])
another_array

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [7]:
another_array[:,3]

array([4, 8, 7])

In [8]:
another_array[2,:]

array([1, 6, 7, 7])

In [9]:
another_array[:,2:3]

array([[2],
       [8],
       [7]])

In [13]:
a=np.array([2,4,3,9,11])
a.sort()
a

array([ 2,  3,  4,  9, 11])

In [15]:
a.argmax()

4

In [16]:
a.argmin()

0

In [17]:
a.argsort()

array([0, 1, 2, 3, 4])

In [19]:
a=np.array([2,34,3,19,11])
a.argsort()

array([0, 2, 4, 3, 1])

In [24]:
a=np.array([2,34,3,19,11])
a.sort()
a

array([ 2,  3, 11, 19, 34])

In [25]:
x = np.array([[1,2,3],[4,5,6]]) # 2 x 3 matrix
y = np.array([[10,11,12],[7,8,9],[1,2,3]]) # 3 x 3 matrix
np.dot(x,y)#also, x.dot(y) or y.dot(x.T)

array([[ 27,  33,  39],
       [ 81,  96, 111]])

In [28]:
x=np.array([[1,8,2],[2,4,2]])
y=np.array([[6,1,5],[1,1,3],[2,4,2]])
np.dot(x,y)

array([[18, 17, 33],
       [20, 14, 26]])

In [ ]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategu='mean')
